In [295]:
from math import sin, cos, log, ceil
import numpy
from matplotlib import pyplot
%matplotlib inline
from matplotlib import rcParams
rcParams['font.family'] = 'serif'
rcParams['font.size'] = 16

In [296]:
ms = 50
g = 9.81
rho = 1.091
A = numpy.pi*(0.5**2)
ve = 325
Cd = 0.15
mp0 = 100
A

0.7853981633974483

In [297]:
h0 = 0
v0 = 0

In [298]:
T = 50
dt = 0.1
N = int(T/dt)+1
t = numpy.linspace(0, T, N)
u = numpy.empty((N, 2))
u[0] = numpy.array([h0, v0])

In [299]:
mp = numpy.empty((N, 1))
for i in range(N):
    if i*dt < 5:
        mp[i] = mp0-20*i*dt
    else:
        mp[i] = 0
mp

array([[ 100.],
       [  98.],
       [  96.],
       [  94.],
       [  92.],
       [  90.],
       [  88.],
       [  86.],
       [  84.],
       [  82.],
       [  80.],
       [  78.],
       [  76.],
       [  74.],
       [  72.],
       [  70.],
       [  68.],
       [  66.],
       [  64.],
       [  62.],
       [  60.],
       [  58.],
       [  56.],
       [  54.],
       [  52.],
       [  50.],
       [  48.],
       [  46.],
       [  44.],
       [  42.],
       [  40.],
       [  38.],
       [  36.],
       [  34.],
       [  32.],
       [  30.],
       [  28.],
       [  26.],
       [  24.],
       [  22.],
       [  20.],
       [  18.],
       [  16.],
       [  14.],
       [  12.],
       [  10.],
       [   8.],
       [   6.],
       [   4.],
       [   2.],
       [   0.],
       [   0.],
       [   0.],
       [   0.],
       [   0.],
       [   0.],
       [   0.],
       [   0.],
       [   0.],
       [   0.],
       [   0.],
       [   0.],
       [

In [300]:
m_dot = numpy.empty((N, 1))
for i in range(N):
    if i*dt < 5:
        m_dot[i] = 20
    else:
        m_dot[i] = 0
m_dot

array([[ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [ 20.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  0.],
       [  

In [301]:
def f(u):
    h = u[0]
    v = u[1]
    return numpy.array([v, -g + (m_dot[n]/(ms+mp[n])*ve)-(rho*v*numpy.abs(v)*A*Cd)/(2*(ms+mp[n]))])

In [302]:
def find_mp(t):
    if t < 5:
        return 100-20*t
    else:
        return 0

In [303]:
def euler_step(u, f, dt):
    return u + dt * f(u)
    
    
            

In [304]:
for n in range(N-1):
    u[n+1] = euler_step(u[n], f, dt)
u

array([[  0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   3.35233333e+00],
       [  3.35233333e-01,   6.76273724e+00],
       ..., 
       [ -1.10625301e+03,  -8.72874160e+01],
       [ -1.11498175e+03,  -8.72891309e+01],
       [ -1.12371066e+03,  -8.72908073e+01]])

In [305]:
h_euler = u[:,0]

In [306]:
idx_euler = numpy.where(h_euler<0.0)[0]
if len(idx_euler) == 0:
    idx_ground_euler = N-1
    print ('has not touched ground yet!')
else:
    idx_ground_euler = idx_euler[0]

In [307]:
u_actual = numpy.empty((idx_ground_euler - 1, 2))
for n in range(idx_ground_euler-1):
    u_actual[n] = u[n]
u_actual

array([[  0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   3.35233333e+00],
       [  3.35233333e-01,   6.76273724e+00],
       [  1.01150706e+00,   1.02317789e+01],
       [  2.03468495e+00,   1.37599957e+01],
       [  3.41068452e+00,   1.73478916e+01],
       [  5.14547367e+00,   2.09959340e+01],
       [  7.24506708e+00,   2.47045500e+01],
       [  9.71552207e+00,   2.84741220e+01],
       [  1.25629343e+01,   3.23049842e+01],
       [  1.57934327e+01,   3.61974176e+01],
       [  1.94131745e+01,   4.01516455e+01],
       [  2.34283390e+01,   4.41678288e+01],
       [  2.78451219e+01,   4.82460602e+01],
       [  3.26697279e+01,   5.23863594e+01],
       [  3.79083639e+01,   5.65886668e+01],
       [  4.35672306e+01,   6.08528377e+01],
       [  4.96525143e+01,   6.51786356e+01],
       [  5.61703779e+01,   6.95657262e+01],
       [  6.31269505e+01,   7.40136697e+01],
       [  7.05283175e+01,   7.85219141e+01],
       [  7.83805089e+01,   8.30897874e+01],
       [  

1.Mass (in kg) of rocket propellant remaining in the rocket at time $t=3.2s$

In [308]:
find_mp(3.2)

36.0

2.Maximum speed of the rocket

In [309]:
v_max = numpy.amax(u_actual[:, 1])
v_max

232.10613341261791

In [310]:
index_vmax = numpy.where(u_actual[:, 1] == v_max)[0]
t = index_vmax[0] * dt
t

5.0

In [311]:
h = u_actual[index_vmax, 0]
h

array([ 523.52283429])

3.Maximum altitude during flight

In [312]:
h_max = numpy.amax(u_actual[:, 0])
h_max

1334.1829454303067

Time at maximum altitude during flight

In [313]:
index_hmax = numpy.where(u_actual[:, 0] == h_max)[0]
t = index_hmax[0] * dt
t

15.700000000000001

4.Time when the rocket impact the ground

In [314]:
t_ground = len(u_actual) * dt
t_ground

37.0

Velocity when the rocket impact the ground

In [315]:
v_ground = u_actual[-1,1]
v_ground

-85.944293265822722

In [316]:
h = u_actual[:, 0]
v = u_actual[:, 1]
h

array([  0.00000000e+00,   0.00000000e+00,   3.35233333e-01,
         1.01150706e+00,   2.03468495e+00,   3.41068452e+00,
         5.14547367e+00,   7.24506708e+00,   9.71552207e+00,
         1.25629343e+01,   1.57934327e+01,   1.94131745e+01,
         2.34283390e+01,   2.78451219e+01,   3.26697279e+01,
         3.79083639e+01,   4.35672306e+01,   4.96525143e+01,
         5.61703779e+01,   6.31269505e+01,   7.05283175e+01,
         7.83805089e+01,   8.66894876e+01,   9.54611366e+01,
         1.04701245e+02,   1.14415495e+02,   1.24609443e+02,
         1.35288510e+02,   1.46457956e+02,   1.58122870e+02,
         1.70288146e+02,   1.82958465e+02,   1.96138274e+02,
         2.09831762e+02,   2.24042843e+02,   2.38775125e+02,
         2.54031891e+02,   2.69816071e+02,   2.86130214e+02,
         3.02976463e+02,   3.20356529e+02,   3.38271657e+02,
         3.56722598e+02,   3.75709582e+02,   3.95232285e+02,
         4.15289797e+02,   4.35880595e+02,   4.57002505e+02,
         4.78652678e+02,